const { readFileSync,writeFileSync }=require('fs')
console.log('start')
const first=readFileSync('./content/first.txt','utf8')
//console.log(first)
writeFileSync('./content/result-sync.txt',`here is the result ${first} `, {flag:'a'})

const result=readFileSync('./content/result-sync.txt','utf8')
//console.log(result)
console.log('done with this task')
console.log('starting the next one')