const names=require('./4-names')
const sayHi=require('./5-utils')
console.log(names)
//console.log(sayHi)
const data=require('./6-alternative-flavor')
//console.log(data)
require('./7-mind-grenade')
sayHi('Susan')
sayHi(names.john)
sayHi(names.peter)